export const boardMembers = [
  {
    id: "joyce-h-schuck",
    name: "JOYCE H. SCHUCK",
    subtitle: "Board Chair & Co-Founder",
    years: "1927–2021",
    description: "Will add description later.",
    image: null, // set this later to require("../assets/board/joyce.jpg"), and for all other members too. Need to ask Deborah for the official board member photos
  },
  {
    id: "stephen-m-schuck",
    name: "STEPHEN M. SCHUCK",
    subtitle: "",
    years: "",
    description: "Will add description later.",
    image: null,
  },
  {
    id: "joe-woodford",
    name: "JOE WOODFORD",
    subtitle: "",
    years: "",
    description: "Will add description later.",
    image: null,
  },
  {
    id: "steven-l-everson",
    name: "STEVEN L. EVERSON",
    subtitle: "",
    years: "",
    description: "Will add description later.",
    image: null,
  },
  {
    id: "kim-shugart",
    name: "KIM SHUGART",
    subtitle: "",
    years: "",
    description: "Will add description later.",
    image: null,
  },
  {
    id: "mike-miles",
    name: "MIKE MILES",
    subtitle: "",
    years: "",
    description: "Will add description later.",
    image: null,
  },
  {
    id: "robert-gardner",
    name: "ROBERT GARDNER",
    subtitle: "",
    years: "",
    description: "Will add description later.",
    image: null,
  },
  {
    id: "lisa-jesse",
    name: "LISA JESSE",
    subtitle: "",
    years: "",
    description: "Will add description later.",
    image: null,
  },
  {
    id: "regina-lewis",
    name: "DR. REGINA LEWIS",
    subtitle: "",
    years: "",
    description: "Will add description later.",
    image: null,
  },
];
